### ISSUE TITLE
Any possibility of using auto-fixing parser?

### ISSUE THREAD

**Issue by azhang** [ju-bezdek/langchain-decorators#10]
My pydantic class seems to always generate errors on the first try, and i end up getting `False` rather than a populated object. I was wondering if you have an idea on how to get https://python.langchain.com/docs/modules/model_io/output_parsers/output_fixing_parser to work using this langchain-decorator

**Comment by ju-bezdek** [comment]
yeah, you can pass `output_parser` as a llm_prompt decorator

alternatively you could use the parser separately (retrieving dict and passing it to the parser)

A little note, I realised this morning thet the OpenAI Auto JSON format feature is no enabled for pydantic output, although it should be. Will release update soon
But it definitely wont work with this one, or at least i don't know immediately how to support it right now.

**Comment by azhang** [comment]
I'm also getting potentially better results by passing in PydanticOutputParser().get_format_instructions() directly.

```python
@llm_prompt
def extract_conversation_entities(
    format_instructions: str = PydanticOutputParser(
        pydantic_object=MyObjectThing
    ).get_format_instructions(),
) -> MyObjectThing:
    """
    ```<prompt:system>
    blahblah blah blah

    {format_instructions}
    ```

    # human message
    ``` <prompt:user>

    ```
    """
    return
    ```

**Comment by ju-bezdek** [comment]
You don't need to do 
```
format_instructions: str = PydanticOutputParser(
        pydantic_object=MyObjectThing
    ).get_format_instructions(),
```

But you DO need to include format_instructions

There are generally two way on how to do it

1. describe them your own way (might be tedious, but sometimes one might do it better than automatic generation, although i didnt have problem with it IF the pydatic object had good anotations) 
2. Let langchain-decorators to describe them (basicaly the same way as you are doing it...) - but the code `get_format_instructions` will be autoexecuted for you **IF** you include them like this:

```
"""
Use this output format:
{FORMAT_INSTRUCTIONS}
"""
```

`FORMAT_INSTRUCTIONS` is a special parameter that will automatically inject get_format_instructions() into you prompt. But you **NEED to place it there**. It is not put to the end of the system prompt automatically becasuse there is just too many ways how one want to do it (me personally used quite lot of them, every scenario has its own use case)

You could also change the name of the placeholder key, if you really wanted to (for instance for lowercase version as you  are using now) by defining it as one of the arguments of `llm_prompt` decorator

**Comment by azhang** [comment]
Awesome! I was getting some trouble earlier using FORMAT_INSTRUCTIONS but it was prob some other thing as it now works great. Thanks for the help!!
