### ISSUE TITLE
How do I select llm at runtime

### ISSUE THREAD

**Issue by azhang** [ju-bezdek/langchain-decorators#12]
I would like to select an llm when I call the decorated function rather than in the llm_prompt decorator. is that supported / possible?

**Comment by ju-bezdek** [comment]
Yes... you can
the way Im doing it defining llms into LLMselector
https://github.com/ju-bezdek/langchain-decorators?tab=readme-ov-file#automatic-llm-selection
`with_llm_rule` has argument `llm_selector_rule_key`

than you can just pass `llm_selector_rule_key` argument to the call ... it is recognised and it will select the matching model (also based on the token count you can descide)
(you can even introduce your own logic based on the arguments as the llm_prompt function implementation that can be doing the decision)


i was thinking of supporting passing in llm directly, alongside any other LlmChain args, but langchain was changing too much there.. now when the 1.0 is already there, it might be good time

**Comment by azhang** [comment]
Got it, thanks! It seems like in order to use it, `llm` has to be undefined in the @llm_prompt(llm=None) decorator, llmchain_decorators must have an llm_selector defined globally,
```
langchain_decorators.GlobalSettings.define_settings(
        llm_selector = my_llm_selector # pass the selector into global settings
    )
```

`llm_selector_rule_key` defined in the .with_llm()

```
    from langchain_decorators import  LlmSelector

my_llm_selector = LlmSelector(
            generation_min_tokens=0, # how much token at min. I for generation I want to have as a buffer
            prompt_to_generation_ratio=1/3 # what percentage of the prompt length should be used for generation buffer 
        )\
        .with_llm_rule(ChatGooglePalm(),max_tokens=512)\  # ... if you want to use LLM whose window is not defined in langchain_decorators.common.MODEL_LIMITS (only OpenAI and Anthropic are there)
        .with_llm(ChatOpenAI(model = "gpt-3.5-turbo"), llm_selector_rule_key="rulekey1")\   # these models are known, therefore we can just pass them and the max window will be resolved
        .with_llm(ChatOpenAI(model = "gpt-3.5-turbo-16k-0613"))\ 
        .with_llm(ChatOpenAI(model = "claude-v1.3-100k"))
```


And then 

        await your_decorated_prompt(
            llm_selector_rule_key="rulekey1",
            other_param="yay",
        )

**Comment by ju-bezdek** [comment]
yes, llm argument on the decorator has priority over selector as it is more concrete...

btw, if you are planning to use something else than openAI's model, i highly recommend looking also here:
[custom_template_block_bulder_llama2.py](https://github.com/ju-bezdek/langchain-decorators/blob/main/code_examples/custom_template_block_bulder_llama2.py)

it describes how to make define model agnostic chat templates by adding the right tokens

**Comment by ju-bezdek** [comment]
btw this is now possible by passing "llm" kwarg directly to the prompt

**Comment by ju-bezdek** [comment]
done in v0.6.0
