### ISSUE TITLE
OpenAI key is exposed in Jupyter Notebook

### ISSUE THREAD

**Issue by jscheel** [ju-bezdek/langchain-decorators#6]
![Screenshot 2023-08-29 at 9 24 20 AM](https://github.com/ju-bezdek/langchain-decorators/assets/211478/6073edd8-2d10-4fe5-803f-4c5e95ea2da3)

**Comment by ju-bezdek** [comment]
thanks for the heads up... 
No worries though,
That API key was disabled a long time ago...:)

I guess I should remove it from the notebook so as not to raise eyebrows, but it's just not very high on my priority list:)

**Comment by ju-bezdek** [comment]
removed so it wont raise an eyebrow anymore
